---

- name: "Set RHEL distribution for the OpenSCAP policy file to use"
  ansible.builtin.set_fact:
    linux_healthcheck_oscap_policy: ssg-rhel{{ansible_distribution_major_version}}-ds

- block:
   - name: "Run OpenSCAP"
     command: oscap xccdf eval \
       --profile {{ linux_healthcheck_oscap_profile }} \
       --results-arf /tmp/oscap-arf.xml \
       --report /tmp/oscap-report.html \
       --fetch-remote-resources \
       /usr/share/xml/scap/ssg/content/{{ linux_healthcheck_oscap_policy }}.xml
     ignore_errors: true

  always:
   - name: "Download OpenSCAP Report for {{ ansible_hostname }}"
     fetch:
       src: "/tmp/oscap-report.html"
       dest: "{{ linux_healthcheck_oscap_reports }}/{{ ansible_hostname }}.html"
       flat: yes

# todo
# cleanup files created
